platform: linux
image_resource:
  type: docker-image
  source: {repository: golang, tag: 1.7-onbuild}

run:
  path: container/build.sh
  
inputs:
- name: container
- name: src
  path: go/src/github.com/hashicorp/terraform

outputs:
- name: out
