jobs:
- name: terraform
  serial: true
  plan:
  - aggregate:
    - get: src
      trigger: true
    - get: container
      trigger: true
  - task: build
    file: container/build.yaml
  - aggregate:
    - put: docker
      params:
        build: out
        tag:   out/version
    - put: s3-linux
      params:
        file: out/terraform-linux-amd64.tgz
        acl: public-read

- name: release-terraform
  plan:
  - get: docker
    passed: [terraform]
    params:
      save: true
  - put: docker
    params:
      load: docker
      tag_as_latest: true

resources:
- name: src
  type: git
  source:
    uri: https://github.com/hmrc/terraform.git
    branch: hmrc-release

- name: container
  type: git
  source:
    uri: https://github.com/desource/container-terraform.git

- name: docker
  type: docker-image
  source:
    repository: quay.io/desource/terraform
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: s3-linux
  type: s3
  source:
    bucket: hmrc-terraform-builds
    versioned_file: terraform-linux-amd64.tgz
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret-key}}
    region_name: eu-west-1
