jobs:
- name: terraform
  serial: true
  plan:
  - aggregate:
    - get: src
      trigger: true
    - get: container
      trigger: true
  - task: build
    file: container/build.yaml
  - aggregate:
    - put: docker
      params:
        build: out
        tag:   out/version

- name: release-terraform
  plan:
  - get: docker
    passed: [terraform]
    params:
      save: true
  - put: docker
    params:
      load: docker
      tag_as_latest: true

resources:
- name: src
  type: git
  source:
    uri: https://github.com/hmrc/terraform.git
    branch: hmrc-release

- name: container
  type: git
  source:
    uri: https://github.com/desource/container-terraform.git

- name: docker
  type: docker-image
  source:
    repository: quay.io/hmrc/terraform
    username: {{quay-io-username}}
    password: {{quay-io-password}}
